---
- name: Copy the jaeger systemd service file
  template:
    src: jaeger.service.j2
    dest: /etc/systemd/system/jaeger.service
    owner: root
    group: root
    mode: 0644
  notify: restart jaeger
